# Controls when action is ran
on: 
  # Ability to run workflow manually from the Actions tab
  workflow_dispatch:
  
# Workflow run is made up of one or more jobs, can be run sequentially or in parallel  
jobs: 

  Development:
    runs-on: ubuntu-latest
    environment: Development environment
    # (steps*) the order of tasks that will be executed as part of the job
    steps:
      # Accesses your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "I am running a job in the Development Environment"
  
  Testing: 
    runs-on: ubuntu-latest
    environment: Testing
    # Runs Testing job after Development Job has successfully completed (Utilize Job name Env. Name)
    needs: Development
    
    # (steps*) the order of tasks that will be executed as part of the job
    steps:
    # Accesses your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "I am running a job in the Testing Environement"
  
  Production: 
    runs-on: ubuntu-latest
    environment: Production
    # Runs Production job after Testing Job has successfully completed
    needs: Testing
    
    # (steps*) the order of tasks that will be executed as part of the job
    steps:
    # Accesses your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "I am running a job in the Production Environement"
